name: Docker Image CI

on:
  push:
    tags:
      - '*'
    branches:
      - main
      
jobs:        
  build-login-publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v3
   
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: building docker image
        run: docker build -t elimuinformatics/a2d2:${GITHUB_REF##*/} -t elimuinformatics/a2d2:latest .

      - name: Publish the Docker image
        run: docker push . --tag elimuinformatics/a2d2:${GITHUB_REF##*/} --tag elimuinformatics/a2d2:latest
